const stage=document.getElementById('stage'),notes=document.getElementById('notes'),counter=document.getElementById('counter');let index=Math.max(0,Math.min(slides.length-1,(Number(location.hash.slice(1))||1)-1)),revealed=false;const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bars(items,key,max,label){return '<div class="chart" role="img" aria-label="'+e(label)+'">'+items.map(m=>{const w=m[key]/max*100;return '<div class="bar-row"><span class="bar-name">'+e(m.name)+(key==='score'?' ($'+m.price.toFixed(3)+')':'')+'</span><div class="bar-track" style="--w:'+w+'%"><div class="bar" style="width:'+w+'%"></div><span class="bar-value">'+m[key]+'</span></div></div>'}).join('')+'</div>'}
function render(){const d=slides[index];let content='';if(d.kind==='cover')content='<p class="eyebrow">LAB 1 · Building &amp; Managing AI Agents</p><h1>Human<br>Agent Loop</h1><img class="logo" src="../assets/riverbot-logo.png" alt="Riverbot Agentics logo"><p><strong>Jordan Ehrman</strong><br>Riverbot Agentics</p><p class="audience">Business students + anyone curious</p>';
else if(d.kind==='finale')content='<img class="wordart" src="../assets/go-do-your-lab.png" alt="GO DO YOUR LAB in rainbow 3D WordArt"><button class="reveal" id="reveal" aria-expanded="'+revealed+'">'+(revealed?'One more time: go do your lab':'A quick thing before you go')+'</button><div class="closing" '+(!revealed?'aria-hidden="true"':'')+'><p><strong>Lab help + general learning: ask me.</strong></p><p>Deeper project support + commercial work:<br>Riverbot Agentics.</p><p><a href="mailto:riverbotagentics@gmail.com" '+(!revealed?'tabindex="-1"':'')+'>riverbotagentics@gmail.com</a></p></div>';
else{content='<h1>'+e(d.title)+'</h1>';if(d.kind==='reddit')content+='<div class="reddit-grid"><img src="../assets/'+e(d.image)+'" alt="Reddit conversation: '+e(d.quote+' — '+d.answer)+'"><div><blockquote>'+e(d.quote)+'</blockquote><p class="answer">'+e(d.answer)+'</p><div class="explain">'+d.body.map(t=>'<p>'+e(t)+'</p>').join('')+'</div></div></div>';
else if(d.kind==='score')content+=bars([...modelData.models].reverse(),'score',70,'LLM Stats composite benchmark scores; API USD per million tokens in labels')+'<p class="chart-caption">Composite score (not a percentage) · Labels: blended API USD / 1M tokens<br>Selected LLM Stats data · 22 Sep 2026 · Your PantherAI access is free.</p>';
else if(d.kind==='size')content+=bars([...sizeData.models].reverse(),'total',800,'Total model parameters in billions')+'<p class="chart-caption">Total parameters, billions. Active subset: gpt-oss-120b 5.1B / DeepSeek-R1 37B.</p>';
else if(d.kind==='access')content+='<a class="url" href="https://pantherai.chapman.edu/login" target="_blank" rel="noopener">'+e(d.body[0])+'</a><ol class="slide-body">'+d.body.slice(1).map(t=>'<li>'+e(t)+'</li>').join('')+'</ol>';
else content+=(d.quote?'<p class="quote">'+e(d.quote)+'</p>':'')+'<div class="slide-body">'+d.body.map(t=>'<p>'+e(t)+'</p>').join('')+'</div>';
if(d.aside&&d.kind!=='score')content+='<p class="aside">'+e(d.aside)+'</p>';content+='<div class="slide-foot"><span>Jordan Ehrman · Riverbot Agentics</span><span>'+String(index+1).padStart(2,'0')+'</span></div>'}
stage.innerHTML='<article class="slide '+d.kind+(revealed?' revealed':'')+'">'+content+'</article>';counter.textContent=(index+1)+' / '+slides.length;document.getElementById('prev').disabled=index===0;document.getElementById('next').disabled=index===slides.length-1&&revealed;notes.innerHTML='<h2>'+e(d.title)+'</h2><p>'+e(d.notes)+'</p>'+d.sources.map(x=>x.startsWith('https://')?'<p class="small"><a href="'+e(x)+'" target="_blank" rel="noopener">'+e(x)+'</a></p>':'<p class="small">'+e(x)+'</p>').join('');if(document.getElementById('reveal'))document.getElementById('reveal').onclick=toggleReveal;history.replaceState(null,'','#'+(index+1));}
function toggleReveal(){revealed=!revealed;const slide=stage.querySelector('.slide'),b=document.getElementById('reveal'),c=stage.querySelector('.closing');slide.classList.toggle('revealed',revealed);b.textContent=revealed?'One more time: go do your lab':'A quick thing before you go';b.setAttribute('aria-expanded',revealed);c.setAttribute('aria-hidden',!revealed);c.querySelector('a').tabIndex=revealed?0:-1;document.getElementById('next').disabled=revealed;}
function go(delta){if(delta>0&&index===slides.length-1){if(!revealed)toggleReveal();return}index=Math.max(0,Math.min(slides.length-1,index+delta));revealed=false;render()}
document.getElementById('prev').onclick=()=>go(-1);document.getElementById('next').onclick=()=>go(1);document.getElementById('notes-toggle').onclick=()=>{notes.hidden=!notes.hidden;document.getElementById('notes-toggle').setAttribute('aria-pressed',!notes.hidden)};document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen()}catch{document.getElementById('fullscreen').textContent='Use browser full screen'}};document.addEventListener('keydown',ev=>{if(['BUTTON','A','INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(['ArrowRight','PageDown',' '].includes(ev.key)){ev.preventDefault();go(1)}if(['ArrowLeft','PageUp'].includes(ev.key)){ev.preventDefault();go(-1)}if(ev.key==='Home'){index=0;revealed=false;render()}if(ev.key==='End'){index=slides.length-1;revealed=false;render()}});render();